/*
 * Copyright 2026 Quentin Ligier. Use of this source code is governed by the MIT license.
 */

{
  parserClass="ch.qligier.jetbrains.plugin.hurlevent.language.parser.HurlParser"
  psiClassPrefix="Hurl"
  psiImplClassSuffix="Impl"
  psiPackage="ch.qligier.jetbrains.plugin.hurlevent.language.psi"
  psiImplPackage="ch.qligier.jetbrains.plugin.hurlevent.language.psi.impl"
  elementTypeHolderClass="ch.qligier.jetbrains.plugin.hurlevent.language.psi.HurlElementTypes"
  elementTypeClass="ch.qligier.jetbrains.plugin.hurlevent.language.psi.HurlElementType"
  tokenTypeClass="ch.qligier.jetbrains.plugin.hurlevent.language.psi.HurlTokenType"
  implements="com.intellij.psi.PsiElement"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  parserUtilClass="ch.qligier.jetbrains.plugin.hurlevent.language.parser.HurlParserUtil"
  generateTokenAccessors=true
  mixin="ch.qligier.jetbrains.plugin.hurlevent.language.psi.impl.HurlPsiImplUtil"
  tokens=[
    T_COMMENT="T_COMMENT"
    T_LPAREN="T_LPAREN"
    T_RPAREN="T_RPAREN"
    T_ESCAPED_TEMPLATE="T_ESCAPED_TEMPLATE"
  ]
}

// Tokens
external T_SPACE
external T_LINE_BREAK
external T_METHOD
external T_HTTP_VERSION
external T_IDENTIFIER
external T_URL
external T_INTEGER_LITERAL
external T_FLOAT_LITERAL
external T_BOOLEAN
external T_NULL
external T_STRING_CONTENT
external T_STRING_START
external T_STRING_END
external T_ESCAPED_CHAR
external T_TEMPLATE_START
external T_TEMPLATE_END
external T_TEMPLATE_IDENTIFIER
external T_TEMPLATE_NUMBER
external T_UNICODE_ESCAPE
external T_HEX_BYTE
external T_DURATION_MS
external T_DURATION_S
external T_DURATION_M
external T_DOT
external T_COLON
external T_EQUALS
external T_SEMICOLON
external T_COMMA
external T_LBRACE
external T_RBRACE
external T_LBRACKET
external T_RBRACKET

// Section types
external T_BASIC_AUTH_SECTION
external T_QUERY_STRING_PARAMS_SECTION
external T_FORM_PARAMS_SECTION
external T_MULTIPART_FORM_DATA_SECTION
external T_COOKIES_SECTION
external T_CAPTURES_SECTION
external T_ASSERTS_SECTION
external T_OPTIONS_SECTION

// Option keywords
external T_AWS_SIGV4_OPTION
external T_CACERT_OPTION
external T_CERT_OPTION
external T_KEY_OPTION
external T_COMPRESSED_OPTION
external T_CONNECT_TO_OPTION
external T_CONNECT_TIMEOUT_OPTION
external T_DELAY_OPTION
external T_LOCATION_OPTION
external T_LOCATION_TRUSTED_OPTION
external T_HEADER_OPTION
external T_HTTP10_OPTION
external T_HTTP11_OPTION
external T_HTTP2_OPTION
external T_HTTP3_OPTION
external T_INSECURE_OPTION
external T_IPV4_OPTION
external T_IPV6_OPTION
external T_LIMIT_RATE_OPTION
external T_MAX_REDIRS_OPTION
external T_MAX_TIME_OPTION
external T_NETRC_OPTION
external T_NETRC_FILE_OPTION
external T_NETRC_OPTIONAL_OPTION
external T_OUTPUT_OPTION
external T_PATH_AS_IS_OPTION
external T_PINNEDPUBKEY_OPTION
external T_PROXY_OPTION
external T_RESOLVE_OPTION
external T_REPEAT_OPTION
external T_RETRY_OPTION
external T_RETRY_INTERVAL_OPTION
external T_SKIP_OPTION
external T_UNIX_SOCKET_OPTION
external T_USER_OPTION
external T_VARIABLE_OPTION
external T_VERBOSE_OPTION
external T_VERY_VERBOSE_OPTION

// Predicate keywords
external T_EQUALS_PREDICATE
external T_NOT_EQUALS_PREDICATE
external T_GREATER_THAN_PREDICATE
external T_GTE_PREDICATE
external T_LESS_THAN_PREDICATE
external T_LTE_PREDICATE
external T_STARTS_WITH_PREDICATE
external T_ENDS_WITH_PREDICATE
external T_CONTAINS_PREDICATE
external T_INCLUDES_PREDICATE
external T_MATCHES_PREDICATE
external T_EXISTS_PREDICATE
external T_IS_INTEGER_PREDICATE
external T_IS_FLOAT_PREDICATE
external T_IS_BOOLEAN_PREDICATE
external T_IS_STRING_PREDICATE
external T_IS_COLLECTION_PREDICATE
external T_IS_EMPTY_PREDICATE
external T_IS_NULL_PREDICATE

// Filter keywords
external T_COUNT_FILTER
external T_URL_DECODE_FILTER
external T_URL_ENCODE_FILTER
external T_HTML_DECODE_FILTER
external T_HTML_ENCODE_FILTER
external T_BASE64_FILTER
external T_BASE64_DECODE_FILTER
external T_BASE32_FILTER
external T_BASE32_DECODE_FILTER
external T_SHA1_FILTER
external T_SHA256_FILTER
external T_SHA512_FILTER
external T_MD5_FILTER
external T_SPLIT_FILTER
external T_JOIN_FILTER
external T_LTRIM_CHARS_FILTER
external T_RTRIM_CHARS_FILTER
external T_TRIM_CHARS_FILTER
external T_LTRIM_FILTER
external T_RTRIM_FILTER
external T_TRIM_FILTER
external T_REPLACE_FILTER

// Query types
external T_JSONPATH_QUERY
external T_XPATH_QUERY
external T_REGEX_QUERY
external T_COOKIE_QUERY
external T_HEADER_QUERY
external T_STATUS_QUERY
external T_URL_QUERY
external T_BODY_QUERY
external T_BYTES_QUERY
external T_DURATION_QUERY
external T_SSL_QUERY
external T_CERTIFICATE_QUERY

// Keywords
external T_FILE_KEYWORD
external T_REDACT_KEYWORD

// ========== Root ==========
hurl_file ::= (entry | line_break)* {
  pin=1
  implements="com.intellij.psi.PsiFile"
  mixin="com.intellij.extapi.psi.PsiFileBase"
  name="HurlFile"
  methods=[getName getFileType]
}

entry ::= line_break* request response? {
  pin=2
  recoverWhile=entry_recover
}

private entry_recover ::= !(T_METHOD | T_HTTP_VERSION | T_URL)

// ========== Request ==========
request ::= line_break* method space url line_break header* request_section* body? {
  pin=2
  recoverWhile=request_recover
}

private request_recover ::= !(T_HTTP_VERSION | T_METHOD)

method ::= T_METHOD
space ::= T_SPACE+
url ::= T_URL | value_string

header ::= line_break* key_value line_break {
  pin=2
}

// Request Sections
request_section ::= basic_auth_section
                 | query_string_params_section
                 | form_params_section
                 | multipart_form_data_section
                 | cookies_section
                 | options_section {
  recoverWhile=section_recover
}

private section_recover ::= !(T_BASIC_AUTH_SECTION | T_QUERY_STRING_PARAMS_SECTION | T_FORM_PARAMS_SECTION
                            | T_MULTIPART_FORM_DATA_SECTION | T_COOKIES_SECTION | T_OPTIONS_SECTION
                            | T_HTTP_VERSION | T_ASSERTS_SECTION | T_CAPTURES_SECTION)

basic_auth_section ::= line_break* T_BASIC_AUTH_SECTION line_break key_value* {
  pin=2
  recoverWhile=params_recover
}

query_string_params_section ::= line_break* T_QUERY_STRING_PARAMS_SECTION line_break key_value* {
  pin=2
  recoverWhile=params_recover
}

form_params_section ::= line_break* T_FORM_PARAMS_SECTION line_break key_value* {
  pin=2
  recoverWhile=params_recover
}

multipart_form_data_section ::= line_break* T_MULTIPART_FORM_DATA_SECTION line_break multipart_form_data_param* {
  pin=2
  recoverWhile=params_recover
}

cookies_section ::= line_break* T_COOKIES_SECTION line_break key_value* {
  pin=2
  recoverWhile=params_recover
}

options_section ::= line_break* T_OPTIONS_SECTION line_break option* {
  pin=2
  recoverWhile=params_recover
}

private params_recover ::= !(key_string | T_BASIC_AUTH_SECTION | T_QUERY_STRING_PARAMS_SECTION
                           | T_FORM_PARAMS_SECTION | T_MULTIPART_FORM_DATA_SECTION | T_COOKIES_SECTION
                           | T_OPTIONS_SECTION | T_HTTP_VERSION | T_CAPTURES_SECTION | T_ASSERTS_SECTION)

// ========== Response ==========
response ::= line_break* http_version space status line_break header* response_section* body? {
  pin=2
  recoverWhile=response_recover
}

private response_recover ::= !(T_METHOD | T_HTTP_VERSION)

http_version ::= T_HTTP_VERSION
status ::= T_INTEGER_LITERAL

// Response Sections
response_section ::= captures_section | asserts_section {
  recoverWhile=response_section_recover
}

private response_section_recover ::= !(T_CAPTURES_SECTION | T_ASSERTS_SECTION | T_METHOD)

captures_section ::= line_break* T_CAPTURES_SECTION line_break capture* {
  pin=2
  recoverWhile=capture_recover
}

private capture_recover ::= !(key_string | T_ASSERTS_SECTION | T_METHOD)

capture ::= line_break* key_string T_COLON query filter* (space T_REDACT_KEYWORD)? line_break {
  pin=2
}

asserts_section ::= line_break* T_ASSERTS_SECTION line_break assert* {
  pin=2
  recoverWhile=assert_recover
}

private assert_recover ::= !(query | T_METHOD)

assert ::= line_break* query filter* space predicate line_break {
  pin=2
}

// ========== Common Elements ==========
key_value ::= line_break* key_string T_COLON value_string line_break? {
  pin=3
  recoverWhile=key_value_recover
}

private key_value_recover ::= !(key_string | line_break | T_LBRACKET)

key_string ::= T_IDENTIFIER | string_literal
value_string ::= string_literal | T_BOOLEAN | T_NULL | T_IDENTIFIER | T_INTEGER_LITERAL | T_FLOAT_LITERAL | T_URL

body ::= line_break* bytes line_break {
  pin=2
}

bytes ::= (T_HEX_BYTE+ | string_literal | json_value)

string_literal ::= T_STRING_START (T_STRING_CONTENT | T_ESCAPED_CHAR | T_UNICODE_ESCAPE | template_expression)* T_STRING_END {
  recoverWhile=string_recover
}

private string_recover ::= !(T_STRING_END)

template_expression ::= T_TEMPLATE_START template_variable (T_DOT template_variable | T_LBRACKET T_INTEGER_LITERAL T_RBRACKET)* filter* T_TEMPLATE_END {
  pin=1
}

template_variable ::= T_TEMPLATE_IDENTIFIER | T_TEMPLATE_NUMBER

// ========== Query ==========
query ::= query_type query_target? {
  recoverWhile=query_recover
}

private query_recover ::= !(filter | space | predicate)

query_type ::= T_JSONPATH_QUERY
            | T_XPATH_QUERY
            | T_REGEX_QUERY
            | T_COOKIE_QUERY
            | T_HEADER_QUERY
            | T_STATUS_QUERY
            | T_URL_QUERY
            | T_BODY_QUERY
            | T_BYTES_QUERY
            | T_DURATION_QUERY
            | T_SSL_QUERY
            | T_CERTIFICATE_QUERY

query_target ::= string_literal | T_IDENTIFIER | T_INTEGER_LITERAL

// ========== Filter ==========
filter ::= space filter_type filter_arg? {
  pin=2
}

filter_type ::= T_COUNT_FILTER
             | T_URL_DECODE_FILTER
             | T_URL_ENCODE_FILTER
             | T_HTML_DECODE_FILTER
             | T_HTML_ENCODE_FILTER
             | T_BASE64_FILTER
             | T_BASE64_DECODE_FILTER
             | T_BASE32_FILTER
             | T_BASE32_DECODE_FILTER
             | T_SHA1_FILTER
             | T_SHA256_FILTER
             | T_SHA512_FILTER
             | T_MD5_FILTER
             | T_SPLIT_FILTER
             | T_JOIN_FILTER
             | T_LTRIM_CHARS_FILTER
             | T_RTRIM_CHARS_FILTER
             | T_TRIM_CHARS_FILTER
             | T_LTRIM_FILTER
             | T_RTRIM_FILTER
             | T_TRIM_FILTER
             | T_REPLACE_FILTER

filter_arg ::= string_literal | T_IDENTIFIER

// ========== Predicate ==========
predicate ::= predicate_type predicate_value? {
  pin=1
  recoverWhile=predicate_recover
}

private predicate_recover ::= !(line_break | T_METHOD)

predicate_type ::= T_EQUALS_PREDICATE
                | T_NOT_EQUALS_PREDICATE
                | T_GREATER_THAN_PREDICATE
                | T_GTE_PREDICATE
                | T_LESS_THAN_PREDICATE
                | T_LTE_PREDICATE
                | T_STARTS_WITH_PREDICATE
                | T_ENDS_WITH_PREDICATE
                | T_CONTAINS_PREDICATE
                | T_INCLUDES_PREDICATE
                | T_MATCHES_PREDICATE
                | T_EXISTS_PREDICATE
                | T_IS_INTEGER_PREDICATE
                | T_IS_FLOAT_PREDICATE
                | T_IS_BOOLEAN_PREDICATE
                | T_IS_STRING_PREDICATE
                | T_IS_COLLECTION_PREDICATE
                | T_IS_EMPTY_PREDICATE
                | T_IS_NULL_PREDICATE

predicate_value ::= json_value | string_literal

// ========== Multipart Form Data ==========
multipart_form_data_param ::= filename_param | key_value

filename_param ::= line_break* key_string T_COLON filename_value line_break {
  pin=3
}

filename_value ::= T_FILE_KEYWORD T_COMMA filename string_part? {
  pin=1
}

filename ::= T_IDENTIFIER | string_literal

string_part ::= T_SEMICOLON string_literal

// ========== Options ==========
option ::= line_break* option_type line_break {
  pin=2
}

option_type ::= aws_sigv4_option
             | cacert_option
             | cert_option
             | key_option
             | compressed_option
             | connect_to_option
             | connect_timeout_option
             | delay_option
             | location_option
             | location_trusted_option
             | header_option
             | http10_option
             | http11_option
             | http2_option
             | http3_option
             | insecure_option
             | ipv4_option
             | ipv6_option
             | limit_rate_option
             | max_redirs_option
             | max_time_option
             | netrc_option
             | netrc_file_option
             | netrc_optional_option
             | output_option
             | path_as_is_option
             | pinnedpubkey_option
             | proxy_option
             | resolve_option
             | repeat_option
             | retry_option
             | retry_interval_option
             | skip_option
             | unix_socket_option
             | user_option
             | variable_option
             | verbose_option
             | very_verbose_option

aws_sigv4_option ::= T_AWS_SIGV4_OPTION T_COLON value_string
cacert_option ::= T_CACERT_OPTION T_COLON filename
cert_option ::= T_CERT_OPTION T_COLON filename_password
key_option ::= T_KEY_OPTION T_COLON value_string
compressed_option ::= T_COMPRESSED_OPTION T_COLON boolean_option
connect_to_option ::= T_CONNECT_TO_OPTION T_COLON value_string
connect_timeout_option ::= T_CONNECT_TIMEOUT_OPTION T_COLON duration_option
delay_option ::= T_DELAY_OPTION T_COLON duration_option
location_option ::= T_LOCATION_OPTION T_COLON boolean_option
location_trusted_option ::= T_LOCATION_TRUSTED_OPTION T_COLON boolean_option
header_option ::= T_HEADER_OPTION T_COLON value_string
http10_option ::= T_HTTP10_OPTION T_COLON boolean_option
http11_option ::= T_HTTP11_OPTION T_COLON boolean_option
http2_option ::= T_HTTP2_OPTION T_COLON boolean_option
http3_option ::= T_HTTP3_OPTION T_COLON boolean_option
insecure_option ::= T_INSECURE_OPTION T_COLON boolean_option
ipv4_option ::= T_IPV4_OPTION T_COLON boolean_option
ipv6_option ::= T_IPV6_OPTION T_COLON boolean_option
limit_rate_option ::= T_LIMIT_RATE_OPTION T_COLON integer_option
max_redirs_option ::= T_MAX_REDIRS_OPTION T_COLON integer_option
max_time_option ::= T_MAX_TIME_OPTION T_COLON integer_option
netrc_option ::= T_NETRC_OPTION T_COLON boolean_option
netrc_file_option ::= T_NETRC_FILE_OPTION T_COLON value_string
netrc_optional_option ::= T_NETRC_OPTIONAL_OPTION T_COLON boolean_option
output_option ::= T_OUTPUT_OPTION T_COLON value_string
path_as_is_option ::= T_PATH_AS_IS_OPTION T_COLON boolean_option
pinnedpubkey_option ::= T_PINNEDPUBKEY_OPTION T_COLON value_string
proxy_option ::= T_PROXY_OPTION T_COLON value_string
resolve_option ::= T_RESOLVE_OPTION T_COLON value_string
repeat_option ::= T_REPEAT_OPTION T_COLON integer_option
retry_option ::= T_RETRY_OPTION T_COLON integer_option
retry_interval_option ::= T_RETRY_INTERVAL_OPTION T_COLON duration_option
skip_option ::= T_SKIP_OPTION T_COLON boolean_option
unix_socket_option ::= T_UNIX_SOCKET_OPTION T_COLON value_string
user_option ::= T_USER_OPTION T_COLON value_string
variable_option ::= T_VARIABLE_OPTION T_COLON variable_definition
verbose_option ::= T_VERBOSE_OPTION T_COLON boolean_option
very_verbose_option ::= T_VERY_VERBOSE_OPTION T_COLON boolean_option

variable_definition ::= T_IDENTIFIER T_EQUALS variable_value

boolean_option ::= T_BOOLEAN | T_IDENTIFIER
integer_option ::= T_INTEGER_LITERAL | T_IDENTIFIER
duration_option ::= T_DURATION_MS | T_DURATION_S | T_DURATION_M | T_INTEGER_LITERAL | T_IDENTIFIER

filename_password ::= filename (T_COLON string_literal)?

variable_value ::= json_value

// ========== JSON Values ==========
json_value ::= json_object
            | json_array
            | json_string
            | json_number
            | T_BOOLEAN
            | T_NULL

json_object ::= T_LBRACE (json_member (T_COMMA json_member)* T_COMMA?)? T_RBRACE {
  recoverWhile=json_recover
}

json_array ::= T_LBRACKET (json_value (T_COMMA json_value)* T_COMMA?)? T_RBRACKET {
  recoverWhile=json_recover
}

json_member ::= (string_literal | T_IDENTIFIER) T_COLON json_value

json_string ::= string_literal

json_number ::= T_FLOAT_LITERAL | T_INTEGER_LITERAL

private json_recover ::= !(T_RBRACE | T_RBRACKET | T_COMMA | line_break)

// ========== Helpers ==========
line_break ::= T_LINE_BREAK+
